//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Core.DPC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChannelStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChannelStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Core.DPC.Resources.ChannelStrings", typeof(ChannelStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autopublication.
        /// </summary>
        public static string AutoPublication {
            get {
                return ResourceManager.GetString("AutoPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines whether article changes should automatically be sent to fronts.
        /// </summary>
        public static string AutoPublicationDesc {
            get {
                return ResourceManager.GetString("AutoPublicationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel provider.
        /// </summary>
        public static string ChannelProvider {
            get {
                return ResourceManager.GetString("ChannelProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines where channel settings is persisted.
        /// </summary>
        public static string ChannelProviderDesc {
            get {
                return ResourceManager.GetString("ChannelProviderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string Channels {
            get {
                return ResourceManager.GetString("Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel status.
        /// </summary>
        public static string ChannelStatus {
            get {
                return ResourceManager.GetString("ChannelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue time.
        /// </summary>
        public static string EnqueueTime {
            get {
                return ResourceManager.GetString("EnqueueTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of errors.
        /// </summary>
        public static string ErrNumBeforeWait {
            get {
                return ResourceManager.GetString("ErrNumBeforeWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of errors before waiting interval.
        /// </summary>
        public static string ErrNumBeforeWaitDesc {
            get {
                return ResourceManager.GetString("ErrNumBeforeWaitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send interval while errors are occuring.
        /// </summary>
        public static string ErrorSendInterval {
            get {
                return ResourceManager.GetString("ErrorSendInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait interval when new notifications are not sent to current receiver.
        /// </summary>
        public static string ErrorSendIntervalDesc {
            get {
                return ResourceManager.GetString("ErrorSendIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current customer code is not working in consolidation mode.
        /// </summary>
        public static string NotConsolidated {
            get {
                return ResourceManager.GetString("NotConsolidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotificationSender service settings have been changed.
        /// </summary>
        public static string NotificationSenderChanged {
            get {
                return ResourceManager.GetString("NotificationSenderChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification timeout.
        /// </summary>
        public static string NotifyTimeout {
            get {
                return ResourceManager.GetString("NotifyTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout of sending to front.
        /// </summary>
        public static string NotifyTimeoutDesc {
            get {
                return ResourceManager.GetString("NotifyTimeoutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package size.
        /// </summary>
        public static string PackageSize {
            get {
                return ResourceManager.GetString("PackageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of simultaneously processed notifications.
        /// </summary>
        public static string PackageSizeDesc {
            get {
                return ResourceManager.GetString("PackageSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication status.
        /// </summary>
        public static string PublishingStatus {
            get {
                return ResourceManager.GetString("PublishingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication time.
        /// </summary>
        public static string PublishingTime {
            get {
                return ResourceManager.GetString("PublishingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send interval.
        /// </summary>
        public static string SendInterval {
            get {
                return ResourceManager.GetString("SendInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval between checks for new notifications to be sent.
        /// </summary>
        public static string SendIntervalDesc {
            get {
                return ResourceManager.GetString("SendIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service start time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotificationSender service start time.
        /// </summary>
        public static string StartTimeDesc {
            get {
                return ResourceManager.GetString("StartTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System settings.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication service is currently unavailable.
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string YourLastTask {
            get {
                return ResourceManager.GetString("YourLastTask", resourceCulture);
            }
        }
    }
}
