//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Core.DPC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Core.DPC.Resources.ControlStrings", typeof(ControlStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is already cached as dictionary.
        /// </summary>
        public static string AlreadyCached {
            get {
                return ResourceManager.GetString("AlreadyCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to editing.
        /// </summary>
        public static string BackToEditing {
            get {
                return ResourceManager.GetString("BackToEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Settings.
        /// </summary>
        public static string CacheSettings {
            get {
                return ResourceManager.GetString("CacheSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To publish these products please click &quot;Publish and Send&quot; button.
        /// </summary>
        public static string ClickPublishAndSendButton {
            get {
                return ResourceManager.GetString("ClickPublishAndSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clone entity.
        /// </summary>
        public static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Prototype Condition.
        /// </summary>
        public static string ClonePrototypeCondition {
            get {
                return ResourceManager.GetString("ClonePrototypeCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL-statement to specify prototype article for cloning.
        /// </summary>
        public static string ClonePrototypeConditionDescription {
            get {
                return ResourceManager.GetString("ClonePrototypeConditionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning Mode.
        /// </summary>
        public static string CloningMode {
            get {
                return ResourceManager.GetString("CloningMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Name.
        /// </summary>
        public static string ContentName {
            get {
                return ResourceManager.GetString("ContentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter.
        /// </summary>
        public static string Converter {
            get {
                return ResourceManager.GetString("Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current send task.
        /// </summary>
        public static string CurrentPartialSendTask {
            get {
                return ResourceManager.GetString("CurrentPartialSendTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Cache Period.
        /// </summary>
        public static string DefaultCachePeriod {
            get {
                return ResourceManager.GetString("DefaultCachePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Mode.
        /// </summary>
        public static string DeletingMode {
            get {
                return ResourceManager.GetString("DeletingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary caching settings.
        /// </summary>
        public static string DictionaryCachingSettings {
            get {
                return ResourceManager.GetString("DictionaryCachingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t publish.
        /// </summary>
        public static string DontPublish {
            get {
                return ResourceManager.GetString("DontPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t remove.
        /// </summary>
        public static string DontRemove {
            get {
                return ResourceManager.GetString("DontRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t wrap in CDATA.
        /// </summary>
        public static string DontWrapInCData {
            get {
                return ResourceManager.GetString("DontWrapInCData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eager loading.
        /// </summary>
        public static string EagerLoading {
            get {
                return ResourceManager.GetString("EagerLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit XML.
        /// </summary>
        public static string EditXml {
            get {
                return ResourceManager.GetString("EditXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish XML Editing.
        /// </summary>
        public static string EndEditXml {
            get {
                return ResourceManager.GetString("EndEditXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit anyway.
        /// </summary>
        public static string ExitAnyway {
            get {
                return ResourceManager.GetString("ExitAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Id.
        /// </summary>
        public static string FieldId {
            get {
                return ResourceManager.GetString("FieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name for Card.
        /// </summary>
        public static string FieldNameForCard {
            get {
                return ResourceManager.GetString("FieldNameForCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide log.
        /// </summary>
        public static string HideLog {
            get {
                return ResourceManager.GetString("HideLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t load.
        /// </summary>
        public static string IgnoreLoading {
            get {
                return ResourceManager.GetString("IgnoreLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in definition.
        /// </summary>
        public static string InDefinition {
            get {
                return ResourceManager.GetString("InDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field type is classifier.
        /// </summary>
        public static string IsClassifier {
            get {
                return ResourceManager.GetString("IsClassifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only.
        /// </summary>
        public static string IsReadOnly {
            get {
                return ResourceManager.GetString("IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Field Name.
        /// </summary>
        public static string JsonFieldName {
            get {
                return ResourceManager.GetString("JsonFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text in &lt;label&gt;.
        /// </summary>
        public static string LabelText {
            get {
                return ResourceManager.GetString("LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last status change time.
        /// </summary>
        public static string LastStatusChangeTime {
            get {
                return ResourceManager.GetString("LastStatusChangeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lazy loading.
        /// </summary>
        public static string LazyLoading {
            get {
                return ResourceManager.GetString("LazyLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load all plain fields.
        /// </summary>
        public static string LoadAllPlainFields {
            get {
                return ResourceManager.GetString("LoadAllPlainFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load as Image.
        /// </summary>
        public static string LoadAsImage {
            get {
                return ResourceManager.GetString("LoadAsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is missing in QP.
        /// </summary>
        public static string MissingInQp {
            get {
                return ResourceManager.GetString("MissingInQp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in definition.
        /// </summary>
        public static string NotInDefinition {
            get {
                return ResourceManager.GetString("NotInDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сoncurrent execution of send tasks is prohibited. Please, wait for completion of the current task..
        /// </summary>
        public static string OnlyOneTask {
            get {
                return ResourceManager.GetString("OnlyOneTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Products to all fronts (live and stage).
        /// </summary>
        public static string PartialSend {
            get {
                return ResourceManager.GetString("PartialSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This utility allows publishing and sending product to fronts along with deleting archived, invisible or ocassionally deleted products.\nYou should enter list of regional or marketing product Ids (possible separators: &lt;span class=&quot;highlighted&quot;&gt;,&lt;/span&gt;&amp;nbsp;&amp;nbsp;&lt;span class=&quot;highlighted&quot;&gt;;&lt;/span&gt;&amp;nbsp;&amp;nbsp;&lt;span class=&quot;highlighted&quot;&gt;space&lt;/span&gt;&amp;nbsp;&amp;nbsp;&lt;span class=&quot;highlighted&quot;&gt;newline&lt;/span&gt;).
        /// </summary>
        public static string PartialSendDescription {
            get {
                return ResourceManager.GetString("PartialSendDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preloading Mode.
        /// </summary>
        public static string PreloadingMode {
            get {
                return ResourceManager.GetString("PreloadingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        public static string ProceedCaching {
            get {
                return ResourceManager.GetString("ProceedCaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process special statuses.
        /// </summary>
        public static string ProcessSpecialStatuses {
            get {
                return ResourceManager.GetString("ProcessSpecialStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id List.
        /// </summary>
        public static string ProductIdList {
            get {
                return ResourceManager.GetString("ProductIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id List to Publish .
        /// </summary>
        public static string ProductIdListToPublish {
            get {
                return ResourceManager.GetString("ProductIdListToPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some products are required to be published before send to fronts.
        /// </summary>
        public static string PublicationRequired {
            get {
                return ResourceManager.GetString("PublicationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish and Send.
        /// </summary>
        public static string PublishAndSend {
            get {
                return ResourceManager.GetString("PublishAndSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Behaviour.
        /// </summary>
        public static string PublishBehaviour {
            get {
                return ResourceManager.GetString("PublishBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query on click.
        /// </summary>
        public static string QueryOnClick {
            get {
                return ResourceManager.GetString("QueryOnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relates to content.
        /// </summary>
        public static string RelateToAnother {
            get {
                return ResourceManager.GetString("RelateToAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relates to this content from content.
        /// </summary>
        public static string RelateToThis {
            get {
                return ResourceManager.GetString("RelateToThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation Condition.
        /// </summary>
        public static string RelationCondition {
            get {
                return ResourceManager.GetString("RelationCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL-statement for article list filtration.
        /// </summary>
        public static string RelationConditionDescription {
            get {
                return ResourceManager.GetString("RelationConditionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to remove field (specify only if it differs from Path).
        /// </summary>
        public static string RemovePath {
            get {
                return ResourceManager.GetString("RemovePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition is the same. No changes to apply..
        /// </summary>
        public static string SameDefinition {
            get {
                return ResourceManager.GetString("SameDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and exit.
        /// </summary>
        public static string SaveAndExit {
            get {
                return ResourceManager.GetString("SaveAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send on Stage only.
        /// </summary>
        public static string SendOnStageOnly {
            get {
                return ResourceManager.GetString("SendOnStageOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Products.
        /// </summary>
        public static string SendProducts {
            get {
                return ResourceManager.GetString("SendProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set null reference.
        /// </summary>
        public static string SetNull {
            get {
                return ResourceManager.GetString("SetNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show log.
        /// </summary>
        public static string ShowLog {
            get {
                return ResourceManager.GetString("ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Id.
        /// </summary>
        public static string TaskId {
            get {
                return ResourceManager.GetString("TaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update or create.
        /// </summary>
        public static string UpdateOrCreate {
            get {
                return ResourceManager.GetString("UpdateOrCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Mode.
        /// </summary>
        public static string UpdatingMode {
            get {
                return ResourceManager.GetString("UpdatingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use existing reference.
        /// </summary>
        public static string UseExisting {
            get {
                return ResourceManager.GetString("UseExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap lines.
        /// </summary>
        public static string WrapLines {
            get {
                return ResourceManager.GetString("WrapLines", resourceCulture);
            }
        }
    }
}
