//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Core.DPC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductCardStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductCardStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Core.DPC.Resources.ProductCardStrings", typeof(ProductCardStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card loaded.
        /// </summary>
        public static string ControlLoaded {
            get {
                return ResourceManager.GetString("ControlLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product display error..
        /// </summary>
        public static string DisplayError {
            get {
                return ResourceManager.GetString("DisplayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front language.
        /// </summary>
        public static string FrontLanguage {
            get {
                return ResourceManager.GetString("FrontLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front status.
        /// </summary>
        public static string FrontStatus {
            get {
                return ResourceManager.GetString("FrontStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front status code.
        /// </summary>
        public static string FrontStatusCode {
            get {
                return ResourceManager.GetString("FrontStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy sorted.
        /// </summary>
        public static string HierarchySorted {
            get {
                return ResourceManager.GetString("HierarchySorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        public static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing on front.
        /// </summary>
        public static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-number values specified.
        /// </summary>
        public static string NotNumberValues {
            get {
                return ResourceManager.GetString("NotNumberValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains unsent changes.
        /// </summary>
        public static string NotRelevant {
            get {
                return ResourceManager.GetString("NotRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product copied.
        /// </summary>
        public static string ProductCopied {
            get {
                return ResourceManager.GetString("ProductCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has no visual presentation.
        /// </summary>
        public static string ProductIsNotVisual {
            get {
                return ResourceManager.GetString("ProductIsNotVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product loaded.
        /// </summary>
        public static string ProductLoaded {
            get {
                return ResourceManager.GetString("ProductLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product localized.
        /// </summary>
        public static string ProductLocalized {
            get {
                return ResourceManager.GetString("ProductLocalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product relevance.
        /// </summary>
        public static string ProductRelevance {
            get {
                return ResourceManager.GetString("ProductRelevance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last published date.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products has been successfully published and sent.
        /// </summary>
        public static string PublishedAndSendSuccess {
            get {
                return ResourceManager.GetString("PublishedAndSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published by.
        /// </summary>
        public static string PublishedBy {
            get {
                return ResourceManager.GetString("PublishedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevance loaded.
        /// </summary>
        public static string RelevanceLoaded {
            get {
                return ResourceManager.GetString("RelevanceLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevance service received.
        /// </summary>
        public static string RelevanceResolved {
            get {
                return ResourceManager.GetString("RelevanceResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevant.
        /// </summary>
        public static string Relevant {
            get {
                return ResourceManager.GetString("Relevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading complete.
        /// </summary>
        public static string Stopwatch {
            get {
                return ResourceManager.GetString("Stopwatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too much products. Please, specify no more than 200.
        /// </summary>
        public static string TooMuchProducts {
            get {
                return ResourceManager.GetString("TooMuchProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect action parameters: content_item_id should be positive.
        /// </summary>
        public static string СontentItemIdPositive {
            get {
                return ResourceManager.GetString("СontentItemIdPositive", resourceCulture);
            }
        }
    }
}
