//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Core.DPC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SendProductActionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SendProductActionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Core.DPC.Resources.SendProductActionStrings", typeof(SendProductActionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products excluded by status.
        /// </summary>
        public static string ExcludedByStatus {
            get {
                return ResourceManager.GetString("ExcludedByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products excluded because of freezing.
        /// </summary>
        public static string ExcludedWithFreezing {
            get {
                return ResourceManager.GetString("ExcludedWithFreezing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no relation access to the following articles.
        /// </summary>
        public static string NoRelationAccess {
            get {
                return ResourceManager.GetString("NoRelationAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found in DPC.
        /// </summary>
        public static string NotFoundInDpc {
            get {
                return ResourceManager.GetString("NotFoundInDpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products not passed filtration by Live channels.
        /// </summary>
        public static string NotPassedByLiveFiltration {
            get {
                return ResourceManager.GetString("NotPassedByLiveFiltration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products not passed filtration by Stage channels.
        /// </summary>
        public static string NotPassedByStageFiltration {
            get {
                return ResourceManager.GetString("NotPassedByStageFiltration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products not passed validation.
        /// </summary>
        public static string NotValidated {
            get {
                return ResourceManager.GetString("NotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed {0} from {1}, Unprocessed products.
        /// </summary>
        public static string PartiallySucceededResult {
            get {
                return ResourceManager.GetString("PartiallySucceededResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products removed from fronts.
        /// </summary>
        public static string RemovedFromFronts {
            get {
                return ResourceManager.GetString("RemovedFromFronts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send new package.
        /// </summary>
        public static string SendNewPackage {
            get {
                return ResourceManager.GetString("SendNewPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All {0} products has been successfully processed.
        /// </summary>
        public static string SucceededResult {
            get {
                return ResourceManager.GetString("SucceededResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your partial send task.
        /// </summary>
        public static string YourPartialSendTask {
            get {
                return ResourceManager.GetString("YourPartialSendTask", resourceCulture);
            }
        }
    }
}
