//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Core.DPC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TaskStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Core.DPC.Resources.TaskStrings", typeof(TaskStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action has been enqueued.
        /// </summary>
        public static string ActionEnqueued {
            get {
                return ResourceManager.GetString("ActionEnqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t process action.
        /// </summary>
        public static string ActionErrorMessage {
            get {
                return ResourceManager.GetString("ActionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles processed: {0}.
        /// </summary>
        public static string ArticlesProcessed {
            get {
                return ResourceManager.GetString("ArticlesProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation is already requested.
        /// </summary>
        public static string CancellationRequested {
            get {
                return ResourceManager.GetString("CancellationRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cancel task because of status.
        /// </summary>
        public static string CannotCancelTask {
            get {
                return ResourceManager.GetString("CannotCancelTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot repeat task because of status.
        /// </summary>
        public static string CannotRepeatTask {
            get {
                return ResourceManager.GetString("CannotRepeatTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click to open.
        /// </summary>
        public static string ClickToOpen {
            get {
                return ResourceManager.GetString("ClickToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit recurrence schedule because task already created by schedule.
        /// </summary>
        public static string EditNotAllowed {
            get {
                return ResourceManager.GetString("EditNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit recurrence schedule.
        /// </summary>
        public static string EditRecurrenceSchedule {
            get {
                return ResourceManager.GetString("EditRecurrenceSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an error occurs while enqueuing action.
        /// </summary>
        public static string ErrorActionEnqueue {
            get {
                return ResourceManager.GetString("ErrorActionEnqueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : articles {1}.
        /// </summary>
        public static string ErrorTemplate {
            get {
                return ResourceManager.GetString("ErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products [{0}] have status {1}, which doesn&apos;t allow publication or they are archived or invisible..
        /// </summary>
        public static string FilteredProducts {
            get {
                return ResourceManager.GetString("FilteredProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastStatusChange.
        /// </summary>
        public static string LastStatusChange {
            get {
                return ResourceManager.GetString("LastStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no available products to publish..
        /// </summary>
        public static string NoProductsToPublish {
            get {
                return ResourceManager.GetString("NoProductsToPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products to unfreeze not found.
        /// </summary>
        public static string NoProductsToUnfreeze {
            get {
                return ResourceManager.GetString("NoProductsToUnfreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough access to relations: {0}.
        /// </summary>
        public static string NoRelationAccess {
            get {
                return ResourceManager.GetString("NoRelationAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Send.
        /// </summary>
        public static string PartialSend {
            get {
                return ResourceManager.GetString("PartialSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processed.
        /// </summary>
        public static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products excluded by status: {0}.
        /// </summary>
        public static string ProductsExcludedByStatus {
            get {
                return ResourceManager.GetString("ProductsExcludedByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products are freezed: {0}.
        /// </summary>
        public static string ProductsFreezed {
            get {
                return ResourceManager.GetString("ProductsFreezed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products not found: {0}.
        /// </summary>
        public static string ProductsNotFound {
            get {
                return ResourceManager.GetString("ProductsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some products have not been processed.
        /// </summary>
        public static string ProductsNotProcessed {
            get {
                return ResourceManager.GetString("ProductsNotProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products are not going to be published: {0}.
        /// </summary>
        public static string ProductsNotToPublish {
            get {
                return ResourceManager.GetString("ProductsNotToPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfreezed products has been send to publication.
        /// </summary>
        public static string ProductsUnfreezed {
            get {
                return ResourceManager.GetString("ProductsUnfreezed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task recurrence schedule.
        /// </summary>
        public static string RecurrenceSchedule {
            get {
                return ResourceManager.GetString("RecurrenceSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rerun.
        /// </summary>
        public static string Rerun {
            get {
                return ResourceManager.GetString("Rerun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfreezing.
        /// </summary>
        public static string Unfreezing {
            get {
                return ResourceManager.GetString("Unfreezing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Last Task.
        /// </summary>
        public static string YourLastTask {
            get {
                return ResourceManager.GetString("YourLastTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Выполняется {
            get {
                return ResourceManager.GetString("Выполняется", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Завершена {
            get {
                return ResourceManager.GetString("Завершена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Новая {
            get {
                return ResourceManager.GetString("Новая", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Отменена {
            get {
                return ResourceManager.GetString("Отменена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Ошибка {
            get {
                return ResourceManager.GetString("Ошибка", resourceCulture);
            }
        }
    }
}
