export { CheckBox } from "./Checkbox";
export { InputText } from "./InputText";
export { InputNumber } from "./InputNumber";
export { InputSearch } from "./InputSearch";
export { InputFile } from "./InputFile";
export { TextArea } from "./Textarea";
export { DatePicker } from "./Datepicker";
export { Select } from "./Select";
export { RadioGroup } from "./RadioGroup";
import "./FormControls.scss";
