// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QA.Core.DPC.DAL;

namespace QA.Core.DPC.DAL.NpgSqlMigrations
{
    [DbContext(typeof(NpgSqlNotificationsModelDataContext))]
    partial class NpgSqlNotificationsModelDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("QA.Core.DPC.DAL.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .HasColumnName("channel");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created");

                    b.Property<string>("Data")
                        .HasColumnName("data");

                    b.Property<int>("DataKey")
                        .HasColumnName("data_key");

                    b.Property<string>("Method")
                        .HasColumnName("method");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.ToTable("messages");
                });
#pragma warning restore 612, 618
        }
    }
}
