//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Core.ProductCatalog.ActionsRunnerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.SpawnedTasks = new HashSet<Task>();
        }
    
        public int ID { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastStatusChangeTime { get; set; }
        public string Name { get; set; }
        public int StateID { get; set; }
        public string Data { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<byte> Progress { get; set; }
        public string Message { get; set; }
        public bool IsCancellationRequested { get; set; }
        public bool IsCancelled { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> ScheduledFromTaskID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public string ExclusiveCategory { get; set; }
        public string Config { get; set; }
        public byte[] BinData { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual TaskState TaskState { get; set; }
        public virtual ICollection<Task> SpawnedTasks { get; set; }
        public virtual Task SheduledFromTask { get; set; }
    }
}
