services:
  impact:
    container_name: impact
    image: "qpcms/dpc-impact:${TAG}"
    restart: always
    ports:
     - '8100:80'
    environment:
     - ElasticBaseAddress=${ELASTIC_HOST}
     - ElasticIndexes__0__Name=qmobile_catalog_products_pg
     - ElasticIndexes__1__Name=qmobile_catalog_products_stage_pg
     - CorsDomains__0=*
     - TZ=Europe/Moscow
    deploy:
      resources:
        limits:
          memory: 512MB
        reservations:
          memory: 256MB
