//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.ProductCatalog.RegionSync.Service {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class RegionSyncServiceSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static RegionSyncServiceSettings defaultInstance = ((RegionSyncServiceSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RegionSyncServiceSettings())));
        
        public static RegionSyncServiceSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dpc.region.sync")]
        public string RegionSyncKey {
            get {
                return ((string)(this["RegionSyncKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DPC Region Sync")]
        public string RegionSyncName {
            get {
                return ((string)(this["RegionSyncName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сервис синхронизации регионов сайта и каталога")]
        public string RegionSyncDescription {
            get {
                return ((string)(this["RegionSyncDescription"]));
            }
        }
    }
}
