@startuml AllowedRelations

object Action {
  <b>Id = 123
  Tariffs = <b>[234, 345]
  MarketingTariff = <b>456
  MarketingDevices = <b>[567]
}

object "Product" as Tariff1 {
  <b>Id = 234
  Type = "Tariff"
  MarketingProduct = <b>456
}

object "Product" as Tariff2 {
  <b>Id = 345
  Type = "Tariff"
  MarketingProduct = <b>456
}

package "Product-MarketingTariff" <<Frame>> {
  object "MarketingProduct" as MarketingTariff {
    <b>Id = 456
    <b>Modified = 15 : 00
    Type = "MarketingTariff"
    Title = "Маркетинговый тариф"
    Category = <b>890
    Actions = <b>[123]
  }

  object TariffCategory {
    <b>Id = 890
    Alias = "tariff"
  }
}



package "Action-MarketingTariff" <<Frame>> {
  object "MarketingProduct" as MarketingTariff1 {
    <b>Id = 456
    <b>Modified = 15 : 00
    Type = "MarketingTariff"
    Description = "Описание тарифа"
    Parent = <b>789
  }

  object "MarketingProduct" as MarketingTariffParent {
    <b>Id = 789
    Alias = "parent_tariff"
  }
}

object "MarketingProduct" as MarketingDevice {
  <b>Id = 567
  <b>Modified = 14 : 00
  Type = "MarketingDevice"
  Description = "Описание оборудования"
  Parent = <b>678
}

object "MarketingProduct" as MarketingDeviceParent {
  <b>Id = 678
  Alias = "parent_device"
}



Action --> Tariff1 : OK
Action --> Tariff2 : OK
Action --> MarketingTariff : OK
Action ..> MarketingTariff1 : BAD\n(Different\nFields)
Tariff1 --> MarketingTariff : OK
Tariff2 --> MarketingTariff : OK
Action --> MarketingDevice : OK
MarketingTariff --> TariffCategory
MarketingTariff ..> Action: BAD\n(Circular\nReference)
MarketingDevice --> MarketingDeviceParent : OK
MarketingTariff1 --> MarketingTariffParent : OK

note "Same <b>Id</b>\nDifferent <b>Fields</b>" as Note
MarketingTariff .. Note
Note .. MarketingTariff1

object "Region" as ParentRegion {
  <b>Id = 1234
  Name = "Российя"
  Parent = <b>null
}

object "Region" as ChildRegion {
  <b>Id = 3456
  Name = "Москва"
  Parent = <b>1234
}

ChildRegion --> ParentRegion : OK
note right of ChildRegion
  Circular <b>Definition
  But Different <b>Ids
endnote

@enduml