//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Core.DPC.Loader.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductLoaderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductLoaderResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Core.DPC.Loader.Resources.ProductLoaderResources", typeof(ProductLoaderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the connection string &apos;{0}&apos; is not specified.
        /// </summary>
        internal static string ERR_CONNECTION_STRING_NO_EXISTS {
            get {
                return ResourceManager.GetString("ERR_CONNECTION_STRING_NO_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задан контент для маппинга. Вероятно, для поля типа EntityField не указан идентификатор контента.
        /// </summary>
        internal static string ERR_CONTENT_DEF_EMPTY {
            get {
                return ResourceManager.GetString("ERR_CONTENT_DEF_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле с названием &apos;{0}&apos; не существует.
        /// </summary>
        internal static string ERR_FIELD_NAME_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ERR_FIELD_NAME_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задана статья &apos;{0}&apos; в контенте Settings.
        /// </summary>
        internal static string ERR_SETTING_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ERR_SETTING_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для получения поля с Id={0} была передана пустая статья.
        /// </summary>
        internal static string ERR_XML_ARTICLE_EMPTY {
            get {
                return ResourceManager.GetString("ERR_XML_ARTICLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статья с Id={0} не существует.
        /// </summary>
        internal static string ERR_XML_ARTICLE_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ERR_XML_ARTICLE_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для контента неверно задан маппинг. ArticleId={0}.
        /// </summary>
        internal static string ERR_XML_CONTENT_MAP_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ERR_XML_CONTENT_MAP_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реальный контент {0} статьи {1} отличается от указанного в конфиге {2}.
        /// </summary>
        internal static string ERR_XML_CONTENTID_DOES_NOT_MATCH_EXPECTED {
            get {
                return ResourceManager.GetString("ERR_XML_CONTENTID_DOES_NOT_MATCH_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У поля с Id={0} тип в мапинге не совпадает с типом в БД.
        /// </summary>
        internal static string ERR_XML_FIELD_DIFF_TYPES {
            get {
                return ResourceManager.GetString("ERR_XML_FIELD_DIFF_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для поля-расширения не задан маппинг. FieldId={0}, ArticleId={1}.
        /// </summary>
        internal static string ERR_XML_FIELD_EXT_MAP_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ERR_XML_FIELD_EXT_MAP_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для поля FieldId={0} Name={1} неверно задан маппинг. ArticleId={2}.
        /// </summary>
        internal static string ERR_XML_FIELD_MAP_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ERR_XML_FIELD_MAP_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить поле с Id={0} у переданной статьи {1} контента {2}.
        /// </summary>
        internal static string ERR_XML_FIELD_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ERR_XML_FIELD_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание простого поля одного и того же контента (Id={0}) не совпадают в разных частях XML. 1) FieldId={1}, FieldName={2}, 2)FieldId={3}, FieldName={4}.
        /// </summary>
        internal static string ERR_XML_PLAIN_FIELDS_NOT_EQUALS {
            get {
                return ResourceManager.GetString("ERR_XML_PLAIN_FIELDS_NOT_EQUALS", resourceCulture);
            }
        }
    }
}
