apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpc-impact-api
  namespace: dpc
  labels:
    app: dpc-impact-api
    logging: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpc-impact-api
  template:
    metadata:
      labels:
        app: dpc-impact-api
    spec:
      containers:
      - name: dpc-impact-api
        image: '||registry||/dpc-impact:||version||'
        envFrom:
        - configMapRef:
            name: dpc-impact-config
        ports:
        - containerPort: 80
        volumeMounts:
        - name: time-config
          mountPath: /etc/localtime
          subPathExpr: $(TZ)
        - name: timezone-config
          mountPath: /etc/timezone
          subPath: TZ
      volumes:
      - name: time-config
        hostPath:
          path: /usr/share/zoneinfo
      - name: timezone-config
        configMap: 
          name: dpc-impact-config
          items:
          - key: TZ
            path: TZ

---
apiVersion: v1
kind: Service
metadata:
  name: dpc-impact-api
  namespace: dpc
spec:
  type: ClusterIP
  selector:
    app: dpc-impact-api
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dpc-impact-api
  namespace: dpc
spec:
  rules:
  - host: '||host||'
    http:
      paths:
      - backend:
          serviceName: dpc-impact-api
          servicePort: 80


