apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dpc-front
  namespace: dpc
spec:
  rules:
  - host: '||front_host||'
    http:
      paths:
      - backend:
          serviceName: dpc-front
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dpc-search-api
  namespace: dpc
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
  - host: '||search_host||'
    http:
      paths:
      - backend:
          serviceName: dpc-search-api
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dpc-sync-api
  namespace: dpc
spec:
  rules:
  - host: '||sync_host||'
    http:
      paths:
      - backend:
          serviceName: dpc-sync-api
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dpc-impact-api
  namespace: dpc
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"  
spec:
  rules:
  - host: '||impact_host||'
    http:
      paths:
      - backend:
          serviceName: dpc-impact-api
          servicePort: 80