//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.ProductCatalog.Validation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RemoteValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RemoteValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.ProductCatalog.Validation.Resources.RemoteValidationMessages", typeof(RemoteValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get some of related marketing products.
        /// </summary>
        public static string Cant_Get_Marketing_Products {
            get {
                return ResourceManager.GetString("Cant_Get_Marketing_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect customer code. {0} expected, {1} received.
        /// </summary>
        public static string CustomerCodeInvalid {
            get {
                return ResourceManager.GetString("CustomerCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate product relations: {0} .
        /// </summary>
        public static string DuplicateRelationsProducts {
            get {
                return ResourceManager.GetString("DuplicateRelationsProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate tariff direction in product parameters: {0}.
        /// </summary>
        public static string DuplicateTariffsAreas {
            get {
                return ResourceManager.GetString("DuplicateTariffsAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate tariff direction in relation matrix parameters: {0}.
        /// </summary>
        public static string DuplicateTariffsAreasMatrix {
            get {
                return ResourceManager.GetString("DuplicateTariffsAreasMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty connection string.
        /// </summary>
        public static string EmptyConnectionString {
            get {
                return ResourceManager.GetString("EmptyConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Alias for current type. Conflicted Ids: {0}.
        /// </summary>
        public static string MarketingProduct_Duplicate_Alias {
            get {
                return ResourceManager.GetString("MarketingProduct_Duplicate_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} not found.
        /// </summary>
        public static string MissingParam {
            get {
                return ResourceManager.GetString("MissingParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some products doesn&apos;t have common regions with related products: {0}.
        /// </summary>
        public static string Products_Different_Regions {
            get {
                return ResourceManager.GetString("Products_Different_Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product contains regions from products: {0}.
        /// </summary>
        public static string ProductsRepeatingRegions {
            get {
                return ResourceManager.GetString("ProductsRepeatingRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related entity is archived. Product: {0}, related articles: {1}.
        /// </summary>
        public static string RelatedEntityIsArchived {
            get {
                return ResourceManager.GetString("RelatedEntityIsArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing products should not match.
        /// </summary>
        public static string Same_Marketing_Products {
            get {
                return ResourceManager.GetString("Same_Marketing_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All regional products for one marketing product should have the same type.
        /// </summary>
        public static string SameTypeMarketingProductProducts {
            get {
                return ResourceManager.GetString("SameTypeMarketingProductProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing and regional products types don&apos;t match.
        /// </summary>
        public static string SameTypeProductMarketingProduct {
            get {
                return ResourceManager.GetString("SameTypeProductMarketingProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting {0} is missing.
        /// </summary>
        public static string Settings_Missing {
            get {
                return ResourceManager.GetString("Settings_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Id doesn&apos;t match (QP and validation).
        /// </summary>
        public static string SiteIdInvalid {
            get {
                return ResourceManager.GetString("SiteIdInvalid", resourceCulture);
            }
        }
    }
}
